server:
  port: 8080
  host: 0.0.0.0
  mode: debug

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: Dazhouquxian2012.
  database: workflow
  auto_migrate: "true"
  params: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  access_expiry: 1h
  refresh_expiry: 168h # 7 days

logging:
  level: "error"
  file_path: "./logs/app.log"